/**
 * FROST cluster configuration — loaded from a JSON file per signer node.
 *
 * Generated by scripts/frost-dkg-bootstrap.ts during initial setup.
 * Each Oracle node loads its own config file at startup.
 */

export interface FrostNodeConfig {
  /** Signer index (1-based, matching DKG participant index). */
  signer_index: number;
  /** Total signers in the group. */
  total_signers: number;
  /** Minimum signers required (threshold). */
  threshold: number;
  /** This signer's DKG key package (opaque JSON from frost-signer). */
  key_package: unknown;
  /** Shared public key package (same for all signers). */
  pubkey_package: unknown;
  /** BIP-340 x-only group public key (hex). */
  group_pubkey: string;
  /** Peer signer endpoints for signing coordination. */
  peers: PeerConfig[];
}

export interface PeerConfig {
  /** Signer index. */
  signer_index: number;
  /** HTTP endpoint (e.g., "http://localhost:4001"). */
  endpoint: string;
  /** API key for authenticating to this peer. */
  api_key?: string;
}

/** Load a FROST node config from a JSON file. */
export function loadFrostNodeConfig(filePath: string): FrostNodeConfig {
  const text = Deno.readTextFileSync(filePath);
  return JSON.parse(text) as FrostNodeConfig;
}

/** Save a FROST node config to a JSON file. */
export function saveFrostNodeConfig(filePath: string, config: FrostNodeConfig): void {
  Deno.writeTextFileSync(filePath, JSON.stringify(config, null, 2));
}

/** Build a ThresholdOracleConfig from a FrostNodeConfig. */
export function toThresholdOracleConfig(config: FrostNodeConfig): import("../../domain/oracle-types").ThresholdOracleConfig {
  return {
    threshold: config.threshold,
    total_signers: config.total_signers,
    signer_pubkeys: config.peers.map(p => String(p.signer_index)),
    group_pubkey: config.group_pubkey,
  };
}
