/**
 * FROST configuration for prediction market Oracle nodes.
 *
 * Extends FrostNodeConfig with a second set of FROST keys for the NO outcome.
 * The YES group uses the standard fields; the NO group uses the `*_no` fields.
 *
 * Generated by scripts/frost-market-dkg-bootstrap.ts during initial setup.
 */

import type { FrostNodeConfig, PeerConfig } from "./config.ts";

/**
 * Per-node FROST config for a prediction market Oracle.
 *
 * Contains key material for BOTH outcome groups (YES and NO).
 * Each signer node loads one of these at startup.
 */
export interface MarketFrostNodeConfig extends FrostNodeConfig {
  // --- YES group (inherited from FrostNodeConfig) ---
  // key_package, pubkey_package, group_pubkey, peers, etc.

  // --- NO group ---
  /** This signer's DKG key package for the NO group (opaque JSON from frost-signer). */
  key_package_no: unknown;
  /** Shared public key package for the NO group (same for all signers). */
  pubkey_package_no: unknown;
  /** BIP-340 x-only group public key for the NO outcome (hex). */
  group_pubkey_no: string;
}

/** Load a market FROST node config from a JSON file. */
export function loadMarketFrostNodeConfig(filePath: string): MarketFrostNodeConfig {
  const text = Deno.readTextFileSync(filePath);
  const config = JSON.parse(text) as MarketFrostNodeConfig;

  // Validate that both groups are present
  if (!config.group_pubkey) {
    throw new Error(`Market FROST config missing group_pubkey (YES group) in ${filePath}`);
  }
  if (!config.group_pubkey_no) {
    throw new Error(`Market FROST config missing group_pubkey_no (NO group) in ${filePath}`);
  }
  if (!config.key_package_no) {
    throw new Error(`Market FROST config missing key_package_no in ${filePath}`);
  }

  return config;
}

/** Save a market FROST node config to a JSON file. */
export function saveMarketFrostNodeConfig(filePath: string, config: MarketFrostNodeConfig): void {
  Deno.writeTextFileSync(filePath, JSON.stringify(config, null, 2));
}

/**
 * Build a standard FrostNodeConfig from the YES group of a MarketFrostNodeConfig.
 *
 * Useful when the signing coordinator needs a plain FrostNodeConfig.
 */
export function toYesFrostNodeConfig(config: MarketFrostNodeConfig): FrostNodeConfig {
  return {
    signer_index: config.signer_index,
    total_signers: config.total_signers,
    threshold: config.threshold,
    key_package: config.key_package,
    pubkey_package: config.pubkey_package,
    group_pubkey: config.group_pubkey,
    peers: config.peers,
  };
}

/**
 * Build a standard FrostNodeConfig from the NO group of a MarketFrostNodeConfig.
 */
export function toNoFrostNodeConfig(config: MarketFrostNodeConfig): FrostNodeConfig {
  return {
    signer_index: config.signer_index,
    total_signers: config.total_signers,
    threshold: config.threshold,
    key_package: config.key_package_no,
    pubkey_package: config.pubkey_package_no,
    group_pubkey: config.group_pubkey_no,
    peers: config.peers,
  };
}
