services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      DEBUG: 0
      AWS_DEFAULT_REGION: us-east-1
    volumes:
      - "./.local/localstack:/var/lib/localstack"
      - "./scripts/localstack-init:/etc/localstack/init/ready.d"
